### ISSUE TITLE
ngl-viewer: module reloading should have a blacklist (numpy, ...)

### ISSUE THREAD

**Issue by jbnoel-gpsw** [gopro/gopro-lib-node.gl#8]
Traceback (most recent call last):
  File "/Users/jbnoel/devel/node.gl/pynodegl-utils/pynodegl_utils/viewer.py", line 875, in _reload_scripts
    self._reload_unsafe(initial_import)
  File "/Users/jbnoel/devel/node.gl/pynodegl-utils/pynodegl_utils/viewer.py", line 834, in _reload_unsafe
    reload(module)
  File "/Users/jbnoel/bundle/stupeflix/lib/python2.7/site-packages/numpy/_globals.py", line 29, in <module>
    raise RuntimeError('Reloading numpy._globals is not allowed')

**Comment by jbnoel-gpsw** [comment]
From Ultron
BLACK_LIST = [
        "posixpath",  # returned when importing os.path
        "pkg_resources",  # name is not the same when importing pkg_resources (builtin)
        "numpy",  # Reloading numpy._globals is not allowed
        "matplotlib",  # issue reloading tri
        "six",  # used by dragon test (six.moves.urllib.parse, import httpbin)
        "nose",  # used by dragon test
        "Queue",  # used by dragon test
        "stashy", "unittest"  # Jarvis legacy
    ]
